# Generated by Django 2.2 on 2019-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
