# Generated by Django 2.2 on 2019-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_page_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='num',
        ),
        migrations.AddField(
            model_name='page',
            name='biography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='business_category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='country_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='insta_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_business_account',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_join_recently',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_private',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_varified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='list_follower',
            field=models.ManyToManyField(related_name='followed_by', to='core.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='list_following',
            field=models.ManyToManyField(related_name='follow', to='core.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='num_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='num_following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='num_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
