# Generated by Django 2.2 on 2019-04-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190419_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='biography',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
