# Generated by Django 2.2 on 2019-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190419_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='country_code',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
